### ISSUE TITLE
Joomla coding standards not installed

### ISSUE THREAD

**Issue by chrisdavenport** [joomla-projects/docker-joomla-cms-phpcs#2]
I get the following error:
`ERROR: the "build/phpcs/Joomla" coding standard is not installed. The installed coding standards are PSR1, PEAR, Zend, PHPCS, PSR2, MySource and Squiz`

Could the coding standards file be included in the docker image?

**Comment by photodude** [comment]
The [joomla coding standard](https://github.com/joomla/coding-standards) is in the final stages for a public alpha release supporting phpcs 2.8.x
https://developer.joomla.org/news/673-preparing-for-phpcs-2-x-support.html

once that version has a tagged alpha release we can add it with composer here (or anywhere)
